### ISSUE TITLE
Os info

### ISSUE THREAD

**Issue by proJM-Coding** [NicklasVraa/NovaOS#1]
Very cool looking os, I may use it in the future. What is this "bloat" that has been removed? Thanks

**Comment by ghost** [comment]
Also, what version is it based on? Will the project become open source? Thanks again.

**Comment by ghost** [comment]
Never mind, I found out it's based on mint 20.3

**Comment by ghost** [comment]
Sorry about all the questions, I just want to know if it's going to be updated to 21.1 and what is the "bloat" that has been removed? Ignore all the past comments sorry.
