### ISSUE TITLE
Make the iso more foss.

### ISSUE THREAD

**Issue by chukfinley** [NicklasVraa/NovaOS#2]
Try to provide more code of iso on github.
Also host it on sourceforge.net.
Provide SHA256SUM.txt

**Comment by NicklasVraa** [comment]
Will definitely look into it. Thank you for the suggestion.

**Comment by NicklasVraa** [comment]
Added ISO to sourceforge and generated a sha256sum hash. Great suggestions :) Most (if not all) of the code is available in my other repositories.

**Comment by chukfinley** [comment]
Great! The theme looks nice!
